### ISSUE TITLE
How to load models?

### ISSUE THREAD

**Issue by nikolayrantsev** [keyth72/SmartGuitarAmp#1]
Hello! 
It's so exciting to discover this library, thank everyone for the effort!
It might be a dummy question, but -  could you please tell how load models? SmartPedal has the dropdown interface option, what about amp?
Thank you!

**Comment by keyth72** [comment]
Glad to hear you are excited about it, and not a dumb question at all.  The amp is intended to be more like a traditional guitar plugin, with no extra setup other than the VST, so the models are packed into the executable when compiling.  Here are the steps to change out the models:

1. Open up the project in Projucer and add your json models as a Resource. Right click "Resources", add existing files, and make sure to check "Binary Resource".

2. Open the Visual Studio solution (or other target IDE). You should see the new .json model files under "Resources" in the solution explorer.

3. Open PluginProcessor.cpp and edit lines 208 or 219 (this determines which model is used on the Lead or Clean channel):
        (208)  WaveNetLoader loader2(BinaryData::bluej_fullD_p0153_json);    --> 
                            WaveNetLoader loader2(BinaryData::YOUR_NEW_LEAD_MODEL_json);

        (219)  WaveNetLoader loader2(BinaryData::bluej_clean_p0088_json);   -->
                            WaveNetLoader loader2(BinaryData::YOUR_NEW_CLEAN_MODEL_json);

    Where "YOUR_NEW...MODEL" is just the filename of your json file. You can edit either one, or both, but keep in mind they are separately trained models.

4. Build SmartAmp in Release mode.

If you have any issues let me know, but that should do it.  If you have new models that you don't mind sharing I'd love to add them to the repo!

**Comment by nikolayrantsev** [comment]
Hi Keith, thanks for the quick feedback and detailed instruction, it's helpful, 

I wanted to experiment and upload the available SmartPedal and WaveNet model into Amp capabilities. 

As far as I understand, the new model creation requires 2 audio samples - from clean in and effect out. 
What about this? I'm dreaming about the super feature - upload one file (e.g. extracted solo stem, converted to FT32 .wav) and get .json with the particular tone. Then use it in the SmartAmp to be able to control EQ and other parameters, 
Please share your thoughts!

**Comment by keyth72** [comment]
I've thought some about that, it might be possible but it would be a very difficult problem to solve. The first part would be extracting a single guitar from the song.  Say you wanted to extract Led Zeppelin's Stairway to Heaven solo guitar; there are lot's of layers in the same frequency range.  I've seen a few different source separation software out there, but none that extract a guitar track yet.  

If this could be done, there would then be the question of how to get a clean track.  For the WaveNet technology, it needs a source signal to apply the "filter" of the WaveNet model over.  Maybe through some method of machine learning you could generate a clean track based on the target track. 

The next problem to tackle is that the WaveNet model is limited by the specific impulse it can handle (I think the paper states somewhere around 50ms). This can be extended at the cost of processing power.  So it can handle distortion pedals and tube amps well, because what you play takes less than 50ms to run through the circuit. Things like reverb and delay extend out longer in time from the initial note, so you'd need a different kind of capture technology for that part of the signal.  

The short answer is, I think it's possible and somebody will figure it out in the near future, but going from this code to that idea is a big leap. Glad you brought it up though!

**Comment by nikolayrantsev** [comment]
Hi Keith, 
Sharing my draft model - it's just fo the testing. Not real amp or pedal yet, it's only a clean guitar recorded and applied amp plugin. I've got very good results using https://github.com/keyth72/PedalNetRT,
Uploaded the custom model in the SmartGuitarAmp and hear something unexpected, like noise, delays, scratches and hyper distortion. The same result with WaveNetVA. Both works fine on the out-the-box models. I've probably built a plugins wrong (Xcode, release, eigen), could you please try the model on your configuration?
My gear and flow:
- macOS 10.15.7 (19H2)
- iRig HD2 (24/192 sound card)
- Ableton 10 lite
- Saved input files as wav, 32, mono with normalization. 
[converted_model.json.zip](https://github.com/keyth72/SmartGuitarAmp/files/5359876/converted_model.json.zip)

Thank you!!

**Comment by nikolayrantsev** [comment]
Update: seems the question is related to the model conversion: https://github.com/keyth72/PedalNetRT/issues/2,
thank you

**Comment by keyth72** [comment]
Issue resolved by reducing model size, closing
